version: '3.8'

services:
  chipereganyu-api:
    depends_on:
      - database_service
    build: .
    container_name: chipereganyu-api
    ports:
      - 7777:8777
    volumes:
      - .:/usr/src/chipereganyu-api
  database_service:
    image: postgres:16-alpine
    container_name: chipereganyu_database
    ports:
      - 5466:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
